language: node_js

node_js: 8

os: linux

install: true

jobs:
  include:
    - stage: Check
      script: ./tools/check_signed_off.sh
    - stage: Build
      script:
        - npm install
        - npm run build
